apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-driven-repo
  namespace: event-driven-repo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-driven-repo
  template:
    metadata:
      labels:
        app: event-driven-repo
    spec:
      containers:
        - name: event-driven-repo-container
          image: ghcr.io/writetojags/event-driven-repo:latest

          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
      imagePullSecrets:
        - name: ghcr-secret      

---

apiVersion: v1
kind: Service
metadata:
  name: event-driven-repo
  namespace: event-driven-repo
spec:
  selector:
    app: event-driven-repo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
